//! SeaORM entity for the `messages` table.
//!
//! Provides the `Model`, `ActiveModel`, `Entity`, `Column`, and `Relation`
//! types generated by [`DeriveEntityModel`].  This entity maps directly to the
//! `messages` table created by migration 0004.

use sea_orm::entity::prelude::*;

/// Row representation of the `messages` table.
///
/// The primary key `id` is a **UUIDv7** - a time-sortable UUID variant whose
/// 48-bit timestamp prefix makes it monotonically increasing.  This property
/// is exploited by [`crate::domain::ports::ChatRepository::list_messages`]
/// to implement efficient keyset pagination:
/// `WHERE id < before_id ORDER BY id DESC LIMIT n`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    /// UUIDv7 - monotonically increasing so it doubles as a time-ordered cursor.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,

    pub room_id: Uuid,
    pub sender_id: Uuid,
    pub content: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
