//! SeaORM entity for the `rooms` table.
//!
//! Provides the `Model`, `ActiveModel`, `Entity`, `Column`, and `Relation`
//! types generated by [`DeriveEntityModel`].  This entity maps directly to the
//! `rooms` table created by migration 0002.

use sea_orm::entity::prelude::*;

/// Row representation of the `rooms` table.
///
/// A room can be either a **direct** (1-to-1) conversation or a **group**
/// conversation.  The `room_type` column stores the discriminant as a plain
/// string and is parsed into [`crate::domain::models::RoomType`] on
/// conversion to the domain model.
///
/// For direct rooms, `direct_room_key` holds a deterministic sorted-UUID
/// string that uniquely identifies the pair of participants.  For group rooms
/// this field is `NULL`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "rooms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,

    /// Stored as a plain string: `"direct"` or `"group"`.
    pub room_type: String,

    /// Title is only set for group rooms.
    pub title: Option<String>,

    /// Deterministic key for direct rooms (`sorted_uuid_a:sorted_uuid_b`).
    /// `NULL` for group rooms.
    #[sea_orm(unique)]
    pub direct_room_key: Option<String>,

    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
