//! SeaORM entity for the `room_users` join table (composite PK).
//!
//! Provides the `Model`, `ActiveModel`, `Entity`, `Column`, and `Relation`
//! types generated by [`DeriveEntityModel`].  This entity maps directly to the
//! `room_users` table created by migration 0003.

use sea_orm::entity::prelude::*;

/// Row representation of the `room_users` join table.
///
/// This is a many-to-many association between [`super::room::Model`] and
/// [`super::user::Model`] that also carries per-membership state (unread
/// counter and last-read pointer).
///
/// The **composite primary key** is `(room_id, user_id)`.  SeaORM handles the
/// composite PK automatically when performing `UPDATE` or `DELETE` operations
/// via [`ActiveModel`] - both columns are included in the `WHERE` clause.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "room_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub room_id: Uuid,

    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,

    pub unread_count: i64,

    pub joined_at: DateTimeWithTimeZone,

    /// ID of the last message the user has read (NULL = no messages read yet).
    pub last_read_message_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
