//! SeaORM entity for the `users` table.
//!
//! Provides the `Model`, `ActiveModel`, `Entity`, `Column`, and `Relation`
//! types generated by [`DeriveEntityModel`].  This entity maps directly to the
//! `users` table created by migration 0001.

use sea_orm::entity::prelude::*;

/// Row representation of the `users` table.
///
/// All fields correspond one-to-one to the database columns.  When converting
/// to the domain type [`crate::domain::models::User`], the `role` string is
/// parsed via [`std::str::FromStr`] into a [`crate::domain::models::UserRole`]
/// variant, and the `DateTimeWithTimeZone` timestamps are re-expressed as
/// `DateTime<Utc>`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,

    pub username: String,

    #[sea_orm(unique)]
    pub email: String,

    pub password_hash: String,

    /// Stored as a plain string: `"user"` or `"admin"`.
    pub role: String,

    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
