//! Application layer - use-case orchestration for Windwatcher.
//!
//! This module groups all **service** types that coordinate domain logic.
//! Services depend exclusively on [`crate::domain`] traits (ports) and must
//! never import anything from the HTTP transport layer ([`axum`], HTTP status
//! codes, etc.) or from database infrastructure ([`sea_orm`], MongoDB drivers,
//! etc.).
//!
//! # Services
//!
//! | Module           | Responsibility                                                 |
//! | ---------------- | -------------------------------------------------------------- |
//! | [`user_service`] | Registration, authentication (Argon2id + JWT), profile lookup  |
//! | [`chat_service`] | Room management, message enqueueing, pagination, read-receipts |
//!
//! # Design notes
//!
//! All services receive their dependencies as `Arc<dyn Port>` trait objects,
//! enabling full unit-testability with mock implementations generated by
//! `mockall`.  See the `#[cfg(test)]` sections in each submodule for
//! examples.
//!
//! Errors propagate as [`crate::error::AppError`] variants; the HTTP layer is
//! responsible for mapping them to appropriate status codes via the
//! [`axum::response::IntoResponse`] implementation in `error.rs`.

pub mod chat_service;
pub mod user_service;
